"""Initial migration

Revision ID: f0005241f116
Revises:
Create Date: 2025-12-09 23:43:13.248834

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0005241f116"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("book", "article", "other", name="entrykind"),
            nullable=False,
        ),
        sa.Column("link", sa.String(length=2048), nullable=True),
        sa.Column(
            "status",
            sa.Enum("planned", "reading", "done", name="entrystatus"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_entries_id"), "entries", ["id"], unique=False)
    op.create_index("ix_entries_kind", "entries", ["kind"], unique=False)
    op.create_index("ix_entries_status", "entries", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_entries_status", table_name="entries")
    op.drop_index("ix_entries_kind", table_name="entries")
    op.drop_index(op.f("ix_entries_id"), table_name="entries")
    op.drop_table("entries")
    # ### end Alembic commands ###
